config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/calculadora/:number1/:number2', to: 'calculadora#home'
  get '/calculadora/:number1/:number2/soma', to: 'calculadora#soma', as: 'soma'
  get '/calculadora/:number1/:number2/subtracao', to: 'calculadora#subtracao', as: 'subtracao'
  get '/calculadora/:number1/:number2/divisao', to: 'calculadora#divisao', as: 'divisao'
  get '/calculadora/:number1/:number2/multiplicacao', to: 'calculadora#multiplicacao', as: 'multiplicacao'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculadora_controller.rb
class CalculadoraController < ApplicationController
    
    def home
        @number1 = params[:number1].to_i
        @number2 = params[:number2].to_i
    end
    
    def soma
        home
        @soma = @number1 + @number2
    end

    def subtracao
        home
        @subtracao = @number1 - @number2
    end

    def divisao
        home
        @divisao = @number1.to_f / @number2.to_f
    end

    def multiplicacao
        home
        @multiplicacao = @number1 * @number2
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculadora/divisao.html.erb
<%= link_to "Soma", soma_path %>
<%= link_to "Subtração", subtracao_path %>
<%= link_to "Divisão", divisao_path %>
<%= link_to "Multiplicação", multiplicacao_path %>

<h1>Number 1 = <%= @number1%></h1>
<h1>Number 2 = <%= @number2%></h1>
<h1>Resultado = <%= @divisao %></h1>

app/views/calculadora/home.html.erb
<%= link_to "Soma", soma_path %>
<%= link_to "Subtração", subtracao_path %>
<%= link_to "Divisão", divisao_path %>
<%= link_to "Multiplicação", multiplicacao_path %>

<h1>Number 1 = <%= @number1%></h1>
<h1>Number 2 = <%= @number2%></h1>

app/views/calculadora/multiplicacao.html.erb
<%= link_to "Soma", soma_path %>
<%= link_to "Subtração", subtracao_path %>
<%= link_to "Divisão", divisao_path %>
<%= link_to "Multiplicação", multiplicacao_path %>

<h1>Number 1 = <%= @number1%></h1>
<h1>Number 2 = <%= @number2%></h1>
<h1>Resultado = <%= @multiplicacao %></h1>

app/views/calculadora/soma.html.erb
<%= link_to "Soma", soma_path %>
<%= link_to "Subtração", subtracao_path %>
<%= link_to "Divisão", divisao_path %>
<%= link_to "Multiplicação", multiplicacao_path %>

<h1>Number 1 = <%= @number1%></h1>
<h1>Number 2 = <%= @number2%></h1>
<h1>Resultado = <%= @soma %></h1>

app/views/calculadora/subtracao.html.erb
<%= link_to "Soma", soma_path %>
<%= link_to "Subtração", subtracao_path %>
<%= link_to "Divisão", divisao_path %>
<%= link_to "Multiplicação", multiplicacao_path %>

<h1>Number 1 = <%= @number1%></h1>
<h1>Number 2 = <%= @number2%></h1>
<h1>Resultado = <%= @subtracao %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aula1Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>